<a href="https://colab.research.google.com/github/Aaditya019Jain/Self-NLP-Projects/blob/main/Transformer_LLM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
with open('the-verdict.txt', 'r', encoding='UTF-8') as f:
  raw_text = f.read()

print(raw_text[:99])

I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


In [ ]:
import re

text = re.split(r'([,.!:;/><"\?_()\']|--|\s)', raw_text)
# print(text)
result = [t for t in text if t.split()]
print(result)

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(', 'Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"', 'The', 'height', 'of', 'his', 'glory', '"', '--', 'that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing', '--', 'his', 'last', 'Chicago', 'sitter', '--', 'deploring', 'his', 'unaccountable', 'abdication', '.', '"', 'Of', 'course', 'it', "'", 's', 'going', 'to', 'send', 'the', 'value', 'of', 'my', 'picture', "'", 'way', 'up', ';', 'but', 'I', 'don', "'", 't', 'think', 'of', 'that', ',

In [ ]:
all_words = sorted(set(result))
print(len(all_words))

1130


In [ ]:
vocab = {word:i for i,word in enumerate(all_words)}

print(vocab)

{'!': 0, '"': 1, "'": 2, '(': 3, ')': 4, ',': 5, '--': 6, '.': 7, ':': 8, ';': 9, '?': 10, 'A': 11, 'Ah': 12, 'Among': 13, 'And': 14, 'Are': 15, 'Arrt': 16, 'As': 17, 'At': 18, 'Be': 19, 'Begin': 20, 'Burlington': 21, 'But': 22, 'By': 23, 'Carlo': 24, 'Chicago': 25, 'Claude': 26, 'Come': 27, 'Croft': 28, 'Destroyed': 29, 'Devonshire': 30, 'Don': 31, 'Dubarry': 32, 'Emperors': 33, 'Florence': 34, 'For': 35, 'Gallery': 36, 'Gideon': 37, 'Gisburn': 38, 'Gisburns': 39, 'Grafton': 40, 'Greek': 41, 'Grindle': 42, 'Grindles': 43, 'HAD': 44, 'Had': 45, 'Hang': 46, 'Has': 47, 'He': 48, 'Her': 49, 'Hermia': 50, 'His': 51, 'How': 52, 'I': 53, 'If': 54, 'In': 55, 'It': 56, 'Jack': 57, 'Jove': 58, 'Just': 59, 'Lord': 60, 'Made': 61, 'Miss': 62, 'Money': 63, 'Monte': 64, 'Moon-dancers': 65, 'Mr': 66, 'Mrs': 67, 'My': 68, 'Never': 69, 'No': 70, 'Now': 71, 'Nutley': 72, 'Of': 73, 'Oh': 74, 'On': 75, 'Once': 76, 'Only': 77, 'Or': 78, 'Perhaps': 79, 'Poor': 80, 'Professional': 81, 'Renaissance': 82, 'Ri

In [ ]:
class tokenizeV1():

  def __init__(self, vocab):
    self.str_to_int = vocab
    self.int_to_str = {i:s for s,i in vocab.items()}

  def encode(self, text):
    tokens = re.split(r'([,.!:;/><"\?_()\']|--|\s)', text)

    tokens = [t for t in tokens if t.strip()]

    token_ids = []

    for token in tokens:
      token_ids.append(self.str_to_int[token])

    return token_ids

  def decode(self, ids):

    text = " ".join(self.int_to_str[token_id] for token_id in ids)

    text = re.sub(r'\s+([,.!:;/><"\?_()\'])', r'\1', text)

    return text

In [ ]:
sentence = "how are you."

tokenizer = tokenizeV1(vocab)

token_ids = tokenizer.encode(sentence)

In [ ]:
tokenizer.decode(token_ids)

'how are you.'

# Tokenizer V2 with |unk| and <|endoftext|>

In [ ]:
words = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)

words = [word for word in words if word.strip()]

words = sorted(set(words))
words.extend(["<|endoftext|>", "<|unk|>"])

vocab = {word:i for i,word in enumerate(words)}

# vocab.extend()
print(vocab)

{'!': 0, '"': 1, "'": 2, '(': 3, ')': 4, ',': 5, '--': 6, '.': 7, ':': 8, ';': 9, '?': 10, 'A': 11, 'Ah': 12, 'Among': 13, 'And': 14, 'Are': 15, 'Arrt': 16, 'As': 17, 'At': 18, 'Be': 19, 'Begin': 20, 'Burlington': 21, 'But': 22, 'By': 23, 'Carlo': 24, 'Chicago': 25, 'Claude': 26, 'Come': 27, 'Croft': 28, 'Destroyed': 29, 'Devonshire': 30, 'Don': 31, 'Dubarry': 32, 'Emperors': 33, 'Florence': 34, 'For': 35, 'Gallery': 36, 'Gideon': 37, 'Gisburn': 38, 'Gisburns': 39, 'Grafton': 40, 'Greek': 41, 'Grindle': 42, 'Grindles': 43, 'HAD': 44, 'Had': 45, 'Hang': 46, 'Has': 47, 'He': 48, 'Her': 49, 'Hermia': 50, 'His': 51, 'How': 52, 'I': 53, 'If': 54, 'In': 55, 'It': 56, 'Jack': 57, 'Jove': 58, 'Just': 59, 'Lord': 60, 'Made': 61, 'Miss': 62, 'Money': 63, 'Monte': 64, 'Moon-dancers': 65, 'Mr': 66, 'Mrs': 67, 'My': 68, 'Never': 69, 'No': 70, 'Now': 71, 'Nutley': 72, 'Of': 73, 'Oh': 74, 'On': 75, 'Once': 76, 'Only': 77, 'Or': 78, 'Perhaps': 79, 'Poor': 80, 'Professional': 81, 'Renaissance': 82, 'Ri

In [ ]:
class tokenizeV2():

  def __init__(self, vocab):
    self.str_to_int = vocab
    self.int_to_str = {i:s for s,i in vocab.items()}

  def encode(self, text):
    all_words = re.split(r'([,.:;?_!"()\']|--|\s)', text)

    preprocessed_text = [word for word in all_words if word.strip()]

    token_ids = []
    for word in preprocessed_text:
      if word in self.str_to_int:
        token_ids.append(self.str_to_int[word])
      else:
        token_ids.append(self.str_to_int['<|unk|>'])

    return token_ids

  def decode(self, token_ids):

    text = " ".join(self.int_to_str[id] for id in token_ids)

    text = re.sub(r'\s+([,.:;?_!"()\'])', r'\1', text)

    return text

In [ ]:
tokenizer = tokenizeV2(vocab)

text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."

text = " <|endoftext|> ".join((text1,text2))

print(text)

print(tokenizer.encode(text))

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.
[1131, 5, 355, 1126, 628, 975, 10, 1130, 55, 988, 956, 984, 722, 988, 1131, 7]


In [ ]:
tokenizer.decode(tokenizer.encode(text))

'<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.'

#Byte Pair Encoding

In [ ]:
! pip install tiktoken

In [ ]:
import importlib
import tiktoken

In [ ]:
tokenizer = tiktoken.get_encoding("gpt2")

text = (
    "Hello do you like tea? <|endoftext|> In the sunlit terraces of someunknownpalace."
)

tokens = tokenizer.encode(text, allowed_special={"<|endoftext|>"})

print(tokens)

[15496, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 286, 617, 34680, 18596, 558, 13]


In [ ]:
text = (
    "Some unknown place"
)

tokens = tokenizer.encode(text, allowed_special={"<|endoftext|>"})

print(tokens)

[4366, 6439, 1295]


In [ ]:
enc_text = tokenizer.encode(raw_text)

print(len(enc_text))
print(enc_text[:7])

5145
[40, 367, 2885, 1464, 1807, 3619, 402]


In [ ]:
for i in range(1,len(enc_text)):
  if(i > 5):
    break
  input_tokens = enc_text[:i]
  desired_token = enc_text[i]
  print(f"{input_tokens} --> {desired_token}")

[40] --> 367
[40, 367] --> 2885
[40, 367, 2885] --> 1464
[40, 367, 2885, 1464] --> 1807
[40, 367, 2885, 1464, 1807] --> 3619


In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

class gptDataset(Dataset):
  def __init__(self, text, tokenizer, context_length, stride=1):
    self.input_ids = []
    self.target_ids = []

    token_ids = tokenizer.encode(text)

    for i in range(0, len(token_ids) - context_length, stride):
      input_chunk = token_ids[i:i+context_length]
      output_chunk = token_ids[i+1:i+1+context_length]
      self.input_ids.append(torch.tensor(input_chunk))
      self.target_ids.append(torch.tensor(output_chunk))

  def __len__(self):
    return len(self.input_ids)

  def __getitem__(self, idx):
    return self.input_ids[idx], self.target_ids[idx]


In [ ]:
def create_dataloader_v1(text, tokenizer, batch_size=8, context_lenght=4, stride=4, shuffle=False, drop_last=True, num_workers=0):

  dataset = gptDataset(text, tokenizer, context_lenght, stride)

  dataloader = DataLoader(
      dataset,
      batch_size = batch_size,
      drop_last=drop_last,
      shuffle=shuffle,
      num_workers=num_workers
  )
  return dataloader

In [ ]:
dataloader = create_dataloader_v1(raw_text, tokenizer=tokenizer, batch_size=8, context_lenght=4, shuffle=False, stride=4)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)

print(inputs)
print(inputs.shape)

tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
torch.Size([8, 4])


In [ ]:
vocab_size = 50257
embedding_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, embedding_dim)

token_embeddings = token_embedding_layer(inputs)

print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [ ]:
context_length = 4
pos_embedding_layer = torch.nn.Embedding(context_length, embedding_dim)
pos_embedding = pos_embedding_layer(torch.arange(context_length))

In [ ]:
final_embedding = token_embeddings + pos_embedding

# Attention

In [ ]:
import torch

x = torch.tensor(
    [[0.43, 0.15, 0.89],  # Your      (x^1)
     [0.55, 0.87, 0.66],  # Journey   (x^2)
     [0.57, 0.85, 0.64],  # starts    (x^3)
     [0.22, 0.58, 0.33],  # with      (x^4)
     [0.77, 0.25, 0.10],  # one       (x^5)
     [0.05, 0.80, 0.55]]  # step      (x^6)
)

query = x[1]

attention_scores = torch.empty(x.shape[0])

for i, x_i in enumerate(x):
  attention_scores[i] = torch.dot(x_i, query)

print(attention_scores)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [ ]:
attention_scores_temp = attention_scores/attention_scores.sum()

print(attention_scores_temp)

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])


In [ ]:
attention_scores_temp2 = torch.exp(attention_scores)/torch.sum(torch.exp(attention_scores))
print(attention_scores_temp2)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])


In [ ]:
final_attended_embeddings = torch.empty(query.shape[0])
for i,x_i in enumerate(x):
  final_attended_embeddings += x_i* attention_scores_temp2[i]
print(final_attended_embeddings)

tensor([7.6249e+09, 6.5148e-01, 5.6831e-01])


In [ ]:
from typing_extensions import final
attention_scores_final = torch.empty(x.shape[0],x.shape[0])
# print(attention_scores_final)

for j,query in enumerate(x):
  attention_score = torch.empty(x.shape[0])
  for i, x_i in enumerate(x):
    attention_score[i] = torch.dot(x_i, query)
  # print(attention_score)
  attention_score = torch.softmax(attention_score, dim=0)
  # print(attention_score)
  attention_scores_final[j] = attention_score

print(attention_scores_final)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [ ]:
attention_scores_final2 = x @ x.T
attention_scores_final2 = torch.softmax(attention_scores_final2, dim=1)
print(attention_scores_final2)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [ ]:
context = attention_scores_final2 @ x
print(context)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


In [ ]:
import torch.nn as nn


class attention_blockV1(nn.Module):
  def __init__(self, inputs, dim_out, bias=False):
    super().__init__()
    self. inputs = inputs
    self. key = nn.Linear(inputs.shape[1], dim_out, bias=bias)
    self. query = nn.Linear(inputs.shape[1], dim_out, bias=bias)
    self. value = nn.Linear(inputs.shape[1], dim_out, bias=bias)

  def forward(self):
    Query = self.query(self.inputs)
    Key = self.key(self.inputs)
    Value = self.value(self.inputs)

    self.attention_score = torch.softmax(Query @ Key.T/(Key.shape[1]**0.5), dim=1)
    context = self.attention_score @ Value

    return context

In [ ]:
attention_block = attention_blockV1(x,2)
print(attention_block.forward())

tensor([[-0.0084, -0.2432],
        [-0.0102, -0.2434],
        [-0.0102, -0.2434],
        [-0.0093, -0.2420],
        [-0.0112, -0.2412],
        [-0.0085, -0.2427]], grad_fn=<MmBackward0>)


# Causal Attention

In [ ]:
import torch
import torch.nn as nn

class causal_attn(nn.Module):
  def __init__(self, dim_in, dim_out, context_length, bias=False, dropout=0.1):
    super().__init__()
    self.dim_out = dim_out
    self.W_query = nn.Linear(dim_in, dim_out, bias=bias)
    self.W_key = nn.Linear(dim_in, dim_out, bias=bias)
    self.W_value = nn.Linear(dim_in, dim_out, bias=bias)
    self.dropout = nn.Dropout(dropout)
    self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1))

  def forward(self, inputs):
    batch_size, context_length, dim_in = inputs.shape
    query = self.W_query(inputs)
    key = self.W_key(inputs)
    value = self.W_value(inputs)

    attention_score = query @ key.transpose(1,2) / (key.shape[1]**0.5)
    attention_score.masked_fill_(
        self.mask.bool()[:context_length, :context_length], -torch.inf)
    attention_score = torch.softmax(attention_score / (key.shape[-1]**0.5), dim=-1)

    attention_score = self.dropout(attention_score)

    context = attention_score @ value

    return context


In [ ]:
inputs = torch.tensor(
    [[0.43, 0.15, 0.89],  # Your      (x^1)
     [0.55, 0.87, 0.66],  # Journey   (x^2)
     [0.57, 0.85, 0.64],  # starts    (x^3)
     [0.22, 0.58, 0.33],  # with      (x^4)
     [0.77, 0.25, 0.10],  # one       (x^5)
     [0.05, 0.80, 0.55]]  # step      (x^6)
)

batch = torch.stack((inputs, inputs), dim=0)

CausalAttn = causal_attn(dim_in=inputs.shape[1], dim_out=2, context_length=inputs.shape[0])
print(CausalAttn.forward(batch))

tensor([[[ 0.0000,  0.0000],
         [-0.0183,  0.3224],
         [-0.0864,  0.1198],
         [-0.0754,  0.2138],
         [-0.0037,  0.1746],
         [-0.0686,  0.1760]],

        [[ 0.0972,  0.4605],
         [-0.0183,  0.3224],
         [-0.0080,  0.2171],
         [-0.0404,  0.2062],
         [-0.0308,  0.2101],
         [-0.0686,  0.1760]]], grad_fn=<UnsafeViewBackward0>)


# MultiHead Attention

In [ ]:
import torch
import torch.nn as nn

class multihead_attn(nn.Module):
  def __init__(self, dim_in, dim_out, context_length, num_head, bias=False, dropout=0.1):
    super().__init__()

    self.heads = nn.ModuleList([
        causal_attn(dim_in=dim_in, dim_out=dim_out, context_length=context_length, bias=bias, dropout=dropout)
        for _ in range(num_head)
    ])

  def forward(self, inputs):
    return torch.cat([head(inputs) for head in self.heads], dim=-1)

In [ ]:
mha = multihead_attn(dim_in=inputs.shape[1], dim_out=2, context_length=inputs.shape[0], num_head=2)
print(mha(batch))

tensor([[[-0.4055,  0.3264, -0.5576,  0.6084],
         [ 0.0829,  0.2996, -0.5007,  0.4173],
         [-0.0241,  0.5061, -0.8554,  0.7580],
         [ 0.0241,  0.4607, -0.7801,  0.6849],
         [ 0.0074,  0.3304, -0.7556,  0.6227],
         [ 0.0361,  0.3348, -0.4258,  0.3777]],

        [[-0.4055,  0.3264, -0.5576,  0.6084],
         [-0.2015,  0.1622, -0.7813,  0.7234],
         [-0.0241,  0.5061, -0.5216,  0.4829],
         [ 0.0241,  0.4607, -0.7801,  0.6849],
         [ 0.0405,  0.4501, -0.7556,  0.6227],
         [ 0.0362,  0.3351, -0.7327,  0.6191]]], grad_fn=<CatBackward0>)


In [ ]:
class multihead_attnV2(nn.Module):
  def __init__(self, dim_in, dim_out, context_length, num_heads, bias=False, dropout=0.1):
    super().__init__()

    self.head_dim = dim_out // num_heads
    self.num_heads = num_heads
    self.dim_out = dim_out
    self.Wq = nn.Linear(dim_in, dim_out, bias=bias)
    self.Wk = nn.Linear(dim_in, dim_out, bias=bias)
    self.Wv = nn.Linear(dim_in, dim_out, bias=bias)

    self.dropout = nn.Dropout(dropout)

    self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1))


  def forward(self, inputs):

    batch_size, context_lenght, dim_in = inputs.shape

    queries = self.Wq(inputs)
    keys = self.Wk(inputs)
    values = self.Wv(inputs)

    queries = queries.view(batch_size, context_length, self.num_heads, self.head_dim)
    keys = queries.view(batch_size, context_length, self.num_heads, self.head_dim)
    values = queries.view(batch_size, context_length, self.num_heads, self.head_dim)


    queries = queries.transpose(1,2)
    keys = keys.transpose(1,2)
    values = values.transpose(1,2)

    attn_score = queries @ keys.transpose(2,3)

    attn_score.masked_fill_(
        self.mask.bool()[:context_length, :context_length], -torch.inf)

    attn_score = attn_score / (keys.shape[-1]**0.5)

    attn_weights = torch.softmax(attn_score, dim=-1)
    attn_weights = self.dropout(attn_weights)

    context = attn_weights @ values

    return context.contiguous().view(batch_size, context_length, self.dim_out)




In [ ]:
class LayerNormalization(nn.Module):
  def __init__(self, emb_dim):
    super().__init__()
    self.eps = 1e-5
    self.scale = nn.Parameter(torch.ones(emb_dim))
    self.shift = nn.Parameter(torch.zeros(emb_dim))

  def forward(self, x):
    mean = x.mean(dim=-1, keepdim=True)
    vari = x.var(dim=-1, keepdim=True, unbiased=False)

    x = (x - mean)/torch.sqrt(vari + self.eps)

    return self.scale*x + self.shift

In [ ]:
class FeedForward(nn.Module):
  def __init__(self, cfg):
    super(). __init__()

    self.layers = nn.Sequential(
        nn.Linear(cfg["emb_dim"], 4*cfg["emb_dim"]),
        GELU(),
        nn.Linear(4*cfg["emb_dim"], cfg["emb_dim"]),
    )

  def forward(self,x):
    return self.layers(x)

# Transformer Block

In [ ]:
import torch
import torch.nn as nn

GPT_CONFIG_124M = {
    "vocab_size": 50257,
    "context_length": 1024,
    "emb_dim": 768,
    "num_heads": 12,
    "num_layers": 12,
    "drop_rate": 0.1,
    "qkv_bias":False
}

cfg = GPT_CONFIG_124M

In [ ]:
class causal_attn(nn.Module):
  def __init__(self, dim_in, dim_out, context_length, bias=False, dropout=0.1):
    super().__init__()
    self.dim_out = dim_out
    self.W_query = nn.Linear(dim_in, dim_out, bias=bias)
    self.W_key = nn.Linear(dim_in, dim_out, bias=bias)
    self.W_value = nn.Linear(dim_in, dim_out, bias=bias)
    self.dropout = nn.Dropout(dropout)
    self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1))

  def forward(self, inputs):
    batch_size, context_length, dim_in = inputs.shape
    query = self.W_query(inputs)
    key = self.W_key(inputs)
    value = self.W_value(inputs)

    attention_score = query @ key.transpose(1,2) / (key.shape[1]**0.5)
    attention_score.masked_fill_(
        self.mask.bool()[:context_length, :context_length], -torch.inf)
    attention_score = torch.softmax(attention_score / (key.shape[-1]**0.5), dim=-1)

    attention_score = self.dropout(attention_score)

    context = attention_score @ value

    return context


In [ ]:
class multihead_attn(nn.Module):
  def __init__(self, dim_in, dim_out, context_length, num_head, bias=False, dropout=0.1):
    super().__init__()

    self.heads = nn.ModuleList([
        causal_attn(dim_in=dim_in, dim_out=dim_out, context_length=context_length, bias=bias, dropout=dropout)
        for _ in range(num_head)
    ])

  def forward(self, inputs):
    return torch.cat([head(inputs) for head in self.heads], dim=-1)

In [ ]:
class LayerNormalization(nn.Module):
  def __init__(self, emb_dim):
    super().__init__()
    self.eps = 1e-5
    self.scale = nn.Parameter(torch.ones(emb_dim))
    self.shift = nn.Parameter(torch.zeros(emb_dim))

  def forward(self, x):
    mean = x.mean(dim=-1, keepdim=True)
    vari = x.var(dim=-1, keepdim=True, unbiased=False)

    x = (x - mean)/torch.sqrt(vari + self.eps)

    return self.scale*x + self.shift

class GELU(nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self, x):
    return 0.5 * x * (1 + torch.tanh(torch.sqrt(torch.tensor(2.0/torch.pi))) * (x + 0.44715 * torch.pow(x, 3)))

class FeedForward(nn.Module):
  def __init__(self, cfg):
    super(). __init__()

    self.layers = nn.Sequential(
        nn.Linear(cfg["emb_dim"], 4*cfg["emb_dim"]),
        GELU(),
        nn.Linear(4*cfg["emb_dim"], cfg["emb_dim"]),
    )

  def forward(self,x):
    return self.layers(x)


In [ ]:
class TransformerBlock(nn.Module):
  def __init__(self, cfg):
    super().__init__()

    self.attn = multihead_attnV2(
        dim_in=cfg["emb_dim"],
        dim_out=cfg["emb_dim"],
        context_length=cfg["context_length"],
        num_heads=cfg["num_heads"],
        dropout=cfg["drop_rate"],
        bias=cfg["qkv_bias"],
    )
    self.ff = FeedForward(cfg)
    self.norm1 = LayerNormalization(emb_dim=cfg["emb_dim"])
    self.norm2 = LayerNormalization(emb_dim=cfg["emb_dim"])
    self.drop_shortcut = nn.Dropout(cfg["drop_rate"])

  def forward(self, x):
   shortcut = x
   x = self.norm1(x)
   x = self.attn(x)
   x = self.drop_shortcut(x)

   x = shortcut + x

   shortcut = x
   x = self.norm2(x)
   x = self.ff(x)
   x = self.drop_shortcut(x)

   x = shortcut + x

   return x


In [ ]:
torch.manual_seed(123)

x = torch.rand(2, 4, 768)
block = TransformerBlock(cfg)
output = block(x)

print("Input Shape:", x.shape)
print("Output Shape:", output.shape)

Input Shape: torch.Size([2, 4, 768])
Output Shape: torch.Size([2, 4, 768])
